spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts?currentSchema=contacts_schema
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
app:
  contacts:
    generate: false

